version: '2.3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        container_name: wes-elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - esnet
    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.0
        container_name: wes-kibana
        ports:
            - 5601:5601
        networks:
            - esnet
        environment:            
            SERVER_HOST: 0.0.0.0
            ELASTICSEARCH_URL: http://wes-elasticsearch:9200
        depends_on:
            - elasticsearch
    redis:
        image: redis
        container_name: wes-redis
        networks:
            - esnet
        ports:
            - 6379:6379
volumes:
    esdata1:
        driver: local
    esdata2:
        driver: local

networks:
    esnet:
        driver: bridge
